vim.keymap.set("n", "<leader>gg", "<cmd>Git<cr>")
vim.keymap.set("n", "<leader>ga", "<cmd>Git add .<cr>")
vim.keymap.set("n", "<leader>gw", "<cmd>Gwrite<cr>")
vim.keymap.set("n", "<leader>gr", "<cmd>Gread<cr>")
vim.keymap.set("n", "<leader>gx", "<cmd>Gremove<cr>")
vim.keymap.set("n", "<leader>gm", "<cmd>Gmove<cr>")
vim.keymap.set("n", "<leader>gc", "<cmd>Gcommit<cr>")
vim.keymap.set("n", "<leader>gb", "<cmd>Gblame<cr>")
vim.keymap.set("n", "<leader>gb", "<cmd>Gblame<cr>")
vim.keymap.set({"n", "v"}, "<leader>dg", "<cmd>diffget<cr>")
vim.keymap.set({"n", "v"}, "<leader>dp", "<cmd>diffput<cr>")
